######################## table with sample --> read_file information ######################

# table with sample --> read_file information
samples_file: datatest/input_MTG4_nano.txt

###################### output location #####################################################

# output location
output_dir: out/MTG4_nano_apptainer_full_test

# read file path
read_file_path: None

#-- master control --#
run_pipeline_steps:  
  alpha_div: True

# temporary file directory
tmp_dir: tmp

#-- execution mode --#
execution:
  mode: apptainer
  apptainer:
    image_dir: ./images
    primary_image: ./images/primary_env_latest.sif
    secondary_image: ./images/secondary_env_latest.sif
    bind_paths:
      - "/tmp"
      - "${PWD}"
      - "${PWD}/datatest"
      - "${PWD}/bin"
      - "${PWD}/ref"
      - "${PWD}/tmp"
      - "${PWD}/out"

#-- snakemake pipeline --#
pipeline:
  snakemake_folder: ./
  export_conda: False
  name: FlaPro
  email: "none"

params:
  shortbred_quantify:
    aligner: diamond #or usearch
    usearch_path: bin/scripts/usearch/usearch11.0.667_i86linux32
    markers: ref/curated_fla_markers_c4.fasta
    pct_length: 0.3
  merge_realcounts:
    merge_script: bin/scripts/merge_realcounts.R
